/*
 * This source file was generated by the Gradle 'init' task
 */
package hacklahoma;
import javax.swing.*;

public class App {}
    public static void main(String[] args) {
        JFrame frame = new JFrame("App");
        frame.setSize(300, 300);
        frame.setResizeable(true);
        frame.toFront();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        DiddyKong dk = new DiddyKong();

        frame.add(dk);
        frame.pack();
        frame.setVisible(true);

    }
}
